const API_KEY = "a005a3ccfcf951bef24afe9668f1b803";

const getMovies = {
  fetchTrending: `/trending/all/week?api_key=${API_KEY}&language=en-US`,
  fetchNetflixOriginals: `/discover/tv?api_key=${API_KEY}&with_networks=213`,
  fetchTopRated: `movie/top_rated?api_key=${API_KEY}&language=en-US`,
  fetchActionMovies: `/discover/movie?api_key=${API_KEY}&with_genres=28`,
  fetchAdventureMovies: `/discover/movie?api_key=${API_KEY}&with_genres=12`,
  fetchScienceFictionMovies: `/discover/movie?api_key=${API_KEY}&with_genres=878`,
  fetchDramaMovies: `/discover/movie?api_key=${API_KEY}&with_genres=18`,
  fetchComedyMovies: `/discover/movie?api_key=${API_KEY}&with_genres=35`,
  fetchRomanceMovies: `/discover/movie?api_key=${API_KEY}&with_genres=10749`,
  fetchFamilyMovies: `/discover/movie?api_key=${API_KEY}&with_genres=10751`,
  fetchWesternMovies: `/discover/movie?api_key=${API_KEY}&with_genres=37`,
  fetchFantasyMovies: `/discover/movie?api_key=${API_KEY}&with_genres=14`,
  fetchHorrorMovies: `/discover/movie?api_key=${API_KEY}&with_genres=27`,
  fetchThrillerMovies: `/discover/movie?api_key=${API_KEY}&with_genres=53`,
  fetchWarMovies: `/discover/movie?api_key=${API_KEY}&with_genres=10752`,
  fetchCrimeMovies: `/discover/movie?api_key=${API_KEY}&with_genres=80`,
  fetchMysteryMovies: `/discover/movie?api_key=${API_KEY}&with_genres=9648`,
  fetchTVMovie: `/discover/movie?api_key=${API_KEY}&with_genres=10770`,
  fetchHistoryMovies: `/discover/movie?api_key=${API_KEY}&with_genres=36`,
  fetchMusicMovies: `/discover/movie?api_key=${API_KEY}&with_genres=10402`,
  fetchDocumentaries: `/discover/movie?api_key=${API_KEY}&with_genres=99`,
};

// const getMovies = {
//   fetchTrending: `/trending/all/week?api_key=${API_KEY}&language=en-US`,
//   fetchNetflixOriginals: `/discover/tv?api_key=${API_KEY}&with_networks=213`,
//   fetchTopRated: `movie/top_rated?api_key=${API_KEY}&language=en-US`,
//   fetchActionMovies: `/discover/movie?api_key=${API_KEY}&with_genres=28`,
//   fetchAdventureMovies: `/discover/movie?api_key=${API_KEY}&with_genres=12`,
//   fetchScienceFictionMovies: `/discover/movie?api_key=${API_KEY}&with_genres=878`,
//   fetchDramaMovies: `/discover/tv?api_key=${API_KEY}&with_genres=18`,
//   fetchComedyMovies: `/discover/tv?api_key=${API_KEY}&with_genres=35`,
//   fetchRomanceMovies: `/discover/tv?api_key=${API_KEY}&with_genres=10749`,
//   fetchFamilyMovies: `/discover/tv?api_key=${API_KEY}&with_genres=10751`,
//   fetchWesternMovies: `/discover/tv?api_key=${API_KEY}&with_genres=37`,
//   fetchFantasyMovies: `/discover/movie?api_key=${API_KEY}&with_genres=14`,
//   fetchHorrorMovies: `/discover/movie?api_key=${API_KEY}&with_genres=27`,
//   fetchThrillerMovies: `/discover/movie?api_key=${API_KEY}&with_genres=53`,
//   fetchWarMovies: `/discover/tv?api_key=${API_KEY}&with_genres=10752`,
//   fetchCrimeMovies: `/discover/tv?api_key=${API_KEY}&with_genres=80`,
//   fetchMysteryMovies: `/discover/tv?api_key=${API_KEY}&with_genres=9648`,
//   fetchTVMovie: `/discover/movie?api_key=${API_KEY}&with_genres=10770`,
//   fetchHistoryMovies: `/discover/tv?api_key=${API_KEY}&with_genres=36`,
//   fetchMusicMovies: `/discover/tv?api_key=${API_KEY}&with_genres=10402`,
//   fetchDocumentaries: `/discover/tv?api_key=${API_KEY}&with_genres=99`,
// };

export default getMovies;
